@startuml
actor Utilisateur
boundary Programme
entity ArgumentParser
entity readCSV
entity validateFile
entity validateTuples
entity linearRegression
entity standardDeviation
entity varianceFromLinearRegression
entity confidenceInterval
entity average

Utilisateur -> Programme : python calculator.py file.csv --linear-regression
Programme -> ArgumentParser : Demande du CSV
Programme <-- ArgumentParser : csvFile
|||
Programme -> readCSV : readTuplesCSV(csvFile)
readCSV -> validateFile
readCSV <-- validateFile : OK
readCSV -> validateTuples
readCSV <-- validateTuples : OK
Programme <-- readCSV : dataset
|||
Programme -> linearRegression : linearRegression(dataset) 
Programme <-- linearRegression : LinearRegression
|||
Programme -> standardDeviation: standardDeviation(dataset, linearRegression)
standardDeviation -> varianceFromLinearRegression: varianceFromLinearRegression(dataset, linearRegression)
standardDeviation <-- varianceFromLinearRegression : varianceFromLinearRegression
Programme <-- standardDeviation : standardDeviation
|||
Programme -> confidenceInterval: confidenceInterval(dataset, linearRegression, standardDeviation, confidence, estimation)
confidenceInterval -> average: average(list_of_x)
confidenceInterval <-- average : averageX
Programme <-- confidenceInterval: confidenceInterval

Utilisateur <-- Programme : ConfidenceInterval
@enduml